DEFINE
	MEASURE MEDIDAS[Total_valor_modalidad_varones] = SUMX(FILTER(BIENES_PATRIMONIALES,RELATED('MODALIDAD_EDUCATIVA'[D_TIPO_SEXO])="Varones"),BIENES_PATRIMONIALES[VALOR_NETO])
	MEASURE MEDIDAS[Total_valor_forma_noescolarizado] = SUMX(FILTER(BIENES_PATRIMONIALES,RELATED('FORMATO_EDUCATIVO'[D_FORMA])="No escolarizada"),BIENES_PATRIMONIALES[VALOR_NETO])
	
EVALUATE
	SUMMARIZECOLUMNS(
		"TOTAL MODALIDAD VARONES",[Total_valor_modalidad_varones],
		"TOTAL FORMA ESCOLARIZADA",[Total_valor_forma_noescolarizado]
	)